### ISSUE TITLE
[04] 사용자 그룹에게 부여되는 정책도 인라인 정책이라고 할 수 있을까?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#1]
O
인라인 정책은 단일 IAM ID(사용자, 사용자 그룹 또는 역할)에 대해 생성되는 정책입니다.
인라인 정책은 정책과 자격 증명을 정확히 1대 1 관계로 유지합니다.
정책을 부여 받는 대상이 누군지는 중요하지 않습니다.

https://docs.aws.amazon.com/ko_kr/IAM/latest/UserGuide/access_policies_managed-vs-inline.html#inline-policies

**Comment by ycheese** [comment]
X
인라인 정책은 유저에게 직접 설정하는 걸 의미한다.

---

**정답:**
O
https://docs.aws.amazon.com/ko_kr/IAM/latest/UserGuide/access_policies_managed-vs-inline.html#inline-policies
정책 부여 자체가 인라인 정책이다.
(대상 : 정책 = 1 : 1)
