### ISSUE TITLE
[05] EC2 인스턴스에 대한 설명으로 옳지 않은 것을 고르시오

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#10]
1. EC2 on Demand: 사용한 만큼 비용을 지불한다
2. EC2 Savings Plans: 다 사용하고 나면 on Demand 가격으로 지불한다
3. Spot Instance: 최대 가격을 정하고 스폿 가격이 그걸 넘으면 인스턴스가 손실된다
4. Dedicated Hosts: 나만의 인스턴스를 나만의 하드웨어에 갖는다

**Comment by ycheese** [comment]
4번입니다.
4번은 전용 인스턴스에 대한 설명입니다.
