### ISSUE TITLE
[05] 보안 그룹 O.X 퀴즈

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#11]
1. 인스턴스는 하나의 보안 그룹만 설정할 수 있다
2. 차단된 트래픽을 인스턴스에서 확인이 가능하다
3. 다른 지역으로 전환하는 경우, 새로운 보안 그룹을 생성해야 한다

**Comment by ycheese** [comment]
1. X
2. X
3. O
