### ISSUE TITLE
[05] EC2 User Data에 대한 설명으로 틀린 것은?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#13]
1) EC2 User Data 스크립트는 머신이 기동될 때 최초 1번 실행된다.
2) EC2 User Data를 통해 서버에 필요한 소프트웨어를 설치할 수 있다.
3) EC2 User Data는 EC2 인스턴스 생성 시 필수로 입력해야 한다.
4) EC2 User Data 스크립트 안의 명령어는 root 권한으로 실행된다.

**Comment by ycheese** [comment]
3번입니다. 옵셔널이에요
