### ISSUE TITLE
[05] 다음과 같은 상황에서 가장 적합한 EC2 인스턴스 옵션은?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#18]
> 장기적인 작업보다는 단기적인 워크로드가 많으며, 필요에 따라 인스턴스를 확장하거나 축소할 수 있어야 한다.
> 서비스 중단 없이 안정적인 성능을 유지하는 것이 중요하며, 예산을 최대한 절약하는 것이 중요하다.

1) On-Demand Instance
2) Reserved
3) Saving Plans
4) Spot Instances

**Comment by ycheese** [comment]
1번입니다.
2,3 번은 장기적인 작업에 적합
4번은 안정적인 성능에 부적합
