### ISSUE TITLE
[06] Elastic IP가 지정된 인스턴스를 중지했다가 재시작할 때 발생하는 일은?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#19]
1) Public IP는 변경되고 Private IP는 변경되지 않는다.
2) Public IP는 변경되지 않고 Private IP는 변경된다.
3) Public IP와 Private IP 모두 변경된다.
4) Public IP와 Private IP 모두 변경되지 않는다.

**Comment by ycheese** [comment]
4번
