### ISSUE TITLE
[06] 다음과 같은 상황에서 네트워크 장애 조치를 간편하게 해결하기 위한 방법은?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#20]
> 같은 애플리케이션을 가동 중인 두 대의 EC2 인스턴스가 있다.
> 이 때 장애가 발생하여 한 인스턴스에서 다른 인스턴스로 프라이빗 IPv4를 통해 액세스해야 하는 상황이다.

1) ALB
2) Elastic IP
3) ENI
4) EC2 Hibernate

**Comment by ycheese** [comment]
ENI
