### ISSUE TITLE
[06] ECS 분할 배치 그룹에 대한 설명 중 틀린 것은?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#21]
1) 하나의 AZ에 최대 7개의 파티션이 존재할 수 있다.
2) 동일 리전의 여러 AZ에 걸쳐 있을 수 있다.
3) 서로 다른 파티션의 인스턴스와 렉을 공유한다.
4) HDFS, HBase, Cassandra, Kafka같은 분산 시스템에 적합하다.

**Comment by ycheese** [comment]
3번
