### ISSUE TITLE
[07] EBS 암호화에 대한 설명 중 틀린 것은?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#23]
1) 암호화된 EBS 볼륨을 생성하면 볼륨 내부 데이터가 전부 암호화된다.
2) 암호화되지 않은 스냅샷을 복사할 땐 자동으로 암호화되지 않는다.
3) 암호화된 볼륨의 스냅샷은 자동으로 암호화된다.
4) 암호화되지 않은 EBS에서 생성한 스냅샷은 암호화되지 않는다.

**Comment by ycheese** [comment]
말장난 문제 붐따드립니다.
