### ISSUE TITLE
[06] EC2 인스턴스를 절전 모드로 설정했을 경우 발생하는 것이 아닌 것은?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#26]
1. 인스턴스의 메모리 상태가 유지된다.
2. 인스턴스를 다시 시작하면 다시 이어서 작업 가능하다.
3. 인스턴스에 대한 요금이 부과되지 않는다.
4. 인스턴스의 Public IP 주소가 해제된다.

**Comment by ycheese** [comment]
3번
