### ISSUE TITLE
[04] IAM 사용자와 IAM Role의 차이점은 무엇일까?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#3]
IAM 사용자는 실제 사람에게 부여하는 권한
IAM Role은 서비스에 부여하는 권한

**Comment by ycheese** [comment]
Policy는 사용자가 AWS 서비스를 이용하게 하는 것
Role은 서비스가 다른 AWS 서비스를 이용하게 하는 것
