### ISSUE TITLE
[08] GWLB에 대한 설명으로 옳지 않은 것은?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#37]
1. GWLB는 Gateway Load Balance의 약자로 AWS에서 제공하는 가장 최신의 로드 밸런서이다.
2. GWLB는 L3 레벨에서 작동한다
3. GWLB는 투명 네트워크 게이트웨이로 VPC 내의 모든 트래픽이 GWLB를 거쳐야 하도록 설정하여 네트워크 트래픽을 통합적으로 관리한다
4. 대상 그룹에 EC2 인스턴스만 등록 가능하다
5. GWLB는 6081번 포트의 GENEVE 프로토콜을 사용한다

**Comment by HYEMSTER** [comment]
4.
> ALB, IP주소 등등 가능
