### ISSUE TITLE
[08] SSL 인증서에 대한 설명으로 옳은 것은?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#38]
1. SSL/TLS 인증서는 클라이언트와 서버 간 통신을 암호화하여 데이터를 안전하게 보호하는 디지털 인증서로 직접 생성하여 사용 가능하다
2. SSL은 TLS의 후속 버전으로, 더 안전하고 강력한 보안을 제공한다
3. SSL/TLS 인증서는 만료 일자가 존재하기 때문에 주기적으로 확인하고 갱신해야 한다
4. SNI는 하나의 리스너로 다수의 SSL 인증서를 가져올 수 있도록 한다
6. SNI는 CLB, ALB, NLB에서 지원한다

**Comment by HYEMSTER** [comment]
3번, 4번
- 5번: CLB에서는 지원하지 않음
- 1번: 내가 직접이 아니라 인증 기관에서 생성한다
