### ISSUE TITLE
[08] 연결 드레이닝에 대한 설명으로 옳지 않은 것은?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#39]
1. ALB, NLB의 경우 등록 취소 지연이라고 부른다
2. 연결 드레이닝은 새로운 인스턴스를 추가하거나 기존 인스턴스를 제거하는 동안에도 서비스가 중단되지 않도록 한다
3. 연결 드레이닝의 장점으로는 서비스 가용성 향상과 유연한 시스템 관리가 있다
4. 연결 드레이닝 시간이 짧아질수록 시스템 성능이 저하될 수 있다
5. 드레이닝 시간 동안 인스턴스는 새로운 연결을 받지 않고, 기존 연결이 모두 종료될 때까지 대기한다

**Comment by HYEMSTER** [comment]
4번~
