### ISSUE TITLE
[08] 고정 세션의 쿠키에 대한 설명으로 옳은 것은?

### ISSUE THREAD

**Issue by ycheese** [thisandthat-lab/aws-certified-solutions-architect-associate#44]
1. 애플리케이션 기반 쿠키는 애플리케이션에서 대상으로 생성된 사용자 정의 쿠키를 의미한다.
2. 애플리케이션 기반 쿠키에서 AWSELB 등의 이름을 쓰는 것이 권장된다.
3. 기간 기반 쿠키는 30초 ~ 7일의 특정 기간을 기반으로 만료된다.
4. 기간 기반 쿠키는 애플리케이션에서 생성된다.

**Comment by HYEMSTER** [comment]
1번~
