### ISSUE TITLE
[08] ASG 스케일링 정책에 대한 설명으로 옳은 것은?

### ISSUE THREAD

**Issue by ycheese** [thisandthat-lab/aws-certified-solutions-architect-associate#45]
1. 알려진 사용 패턴을 기반으로 스케일링을 예상 하여 최소 용량을 늘리는 형태의 정책은 예측 스케일링이다.
2. 예약 스케일링은 반복되는 패턴과 주기적인 데이터가 있는 경우 매우 유용하게 쓰이는 정책이다.
3. 단순/단계 스케일링은 CloudWatch 경보를 정의하여 ASG에 용량 단위를 추가/제거할 때 알람이 발생하도록 한다.
4. 동적 스케일링은 다른 정책들에 비해 설정이 까다로우니 주의한다.

**Comment by HYEMSTER** [comment]
3번~
