### ISSUE TITLE
[09] RDS에 대한 설명으로 옳지 않은 것은?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#46]
1. RDS는 관리형 관계형 데이터베이스 서비스로 모니터링 대시보드를 통해 성능 모니터링이 가능하다
2. 읽기 전용 복제본은 비동기식으로 복제되며, 최대 15개까지 생성 가능하다
3. 읽기 전용 복제본을 주 데이터베이스로로 승격 가능하다
4. 단일 AZ에서 다중 AZ로 전환 시, 데이터베이스가 중단될 수도 있기 때문에 반드시 조치 후 전환해야 한다
5. 동일 리전 내에 있는 읽기 전용 복제본은 다른 AZ 간 데이터 전송 비용이 발생하지 않지만, 서로 다른 리전에 있는 경우 복제 비용이 발생한다

**Comment by ycheese** [comment]
4번
