### ISSUE TITLE
[09] Redis와 Memcached에 대한 설명으로 옳지 않은 것은?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#48]
1. Redis는 다중 AZ, 자동 장애 조치 등의 기능과 함께 고가용성을 제공한다
2. Redis는 AOF 지속성을 통해 데이터 보존이 가능하다
3. Redis는 Set와 Sorted Set와 같은 고급 데이터 구조를 지원한다
4. Memcached는 멀티 스레드를 지원하여 데이터를 빠르게 처리 가능하게 한다
5. Redis와 Memcached는 둘 다 복제 가능한 캐시로 데이터 손실에 예민한 경우에도 사용 가능하다

**Comment by ycheese** [comment]
5번
