### ISSUE TITLE
[09] RDS에 관한 설명으로 옳지 않은 것은?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#55]
1. Read Replica 복제는 비동기적으로 이루어지므로 최종적 일관성을 가진다.
2. 다중 AZ에서 재해 복구 시에는 중단이 발생한다.
3. 읽기 복제본도 재해 복구를 위해 다중 AZ로 사용할 수 있다.
4. 동일 리전 내에서 RDS 읽기 복제본을 사용할 경우 비용이 발생하지 않는다.

**Comment by ycheese** [comment]
2번
