### ISSUE TITLE
[09] Aurora 고가용성 및 읽기 확장성 관련 설명으로 옳은 것은?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#56]
1. 2개 이상의 인스턴스가 쓰기 작업을 담당한다.
2. 최대 10개의 읽기 복제본이 읽기 작업을 처리한다.
3. 교차 리전 복제는 지원하지 않는다.
4. 마스터 인스턴스에 문제가 생기면 읽기 복제본 중 하나가 마스터로 승격된다.

**Comment by ycheese** [comment]
4번
