### ISSUE TITLE
[09] 아래와 같은 상황에서 가장 빠르고 효율적인 방법은?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#57]
> Aurora 데이터베이스를 사용중이며 프로덕션 데이터베이스에 영향을 주지 않고 신속하게 스테이징 환경을 설정하고싶다.
1. 스냅샷을 찍고 새 DB 인스턴스로 복원한다.
2. 새로운 Aurora DB 클러스터를 복제한다.
3. S3에서 백업 파일을 이용해 새 Aurora 클러스터로 복원한다.
4. 새로운 Aurora 인스턴스를 수동으로 생성하고 데이터를 마이그레이션한다.

**Comment by ycheese** [comment]
2번
