### ISSUE TITLE
[10] 다음 중 CNAME과 Alias 레코드에 대한 설명으로 옳은 것은?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#58]
1. CNAME은 루트 도메인에서도 사용할 수 있다.
2. Alias는 AWS 리소스를 가리키며, 루트 도메인과 서브 도메인 모두에서 사용할 수 있다.
3. CNAME과 Alias 모두 TTL을 설정할 수 있다.
4. Alias는 다른 호스트 이름을 가리키며, 루트 도메인에서는 사용할 수 없다.

**Comment by ycheese** [comment]
2번
