### ISSUE TITLE
[10] 아래와 같은 상황에서 적절한 설정은?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#59]
> 가중치 기반 라우팅 정책을 사용중이다.
> 특정 서버에 문제가 발생하여 더 이상 해당 서버로 트래픽을 보내지 않고자 한다.
1. 해당 서버의 DNS 레코드를 삭제한다.
2. 해당 서버의 가중치를 0으로 설정한다.
3. 모든 서버의 가중치를 동일하게 설정한다.
4. 해당 서버에 Health Check를 설정하지 않는다.

**Comment by ycheese** [comment]
2번
