### ISSUE TITLE
[10] 아래 항목 중 '서울' 리전으로 연결되는 케이스 2가지를 고르세요.

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#60]
> 현재 사용자의 위치는 '서울'이다.
> 현재 '서울'에서 가장 낮은 지연시간을 가진 리전은 '도쿄'이다.
1. Low-latency 정책 사용
2. Geolocation 정책 사용
3. 도쿄에 가중치를 둔 Geoproximity 정책 사용
4. 서울에 가중치를 둔 Geoproximity 정책 사용

**Comment by ycheese** [comment]
2, 4번
