### ISSUE TITLE
[10] Route 53에 대한 설명으로 옳지 않은 것은?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#64]
1. A 레코드는 IPv6 주소, AAAA 레코드는 IPv4 주소, CNAME 레코드는 다른 호스트 이름으로 매핑한다.
2. TTL DNS 리졸버에서 레코드가 캐싱되는 시간이다.
3. 프라이빗 호스팅 존은 VPC 내부에서만 접근 가능하다.
4. Route 53을 사용하려면 비용이 발생한다.

**Comment by ycheese** [comment]
1번
