### ISSUE TITLE
[10] 라우팅 정책에 대한 설명으로 옳지 않은 것은?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#65]
1. 라우팅 정책은 Route 53이 DNS 쿼리에 어떻게 응답할지를 결정하는 방식이다.
2. 가중치 기반 라우팅 정책을 사용할 때 가중치의 합은 100이 되어야 한다.
3. 장애 조치 레코드로는 기본과 보조만 존재한다.
4. 지리 위치 라우팅은 실제 위치 기반으로 한다.

**Comment by ycheese** [comment]
2번
