### ISSUE TITLE
[10] 대화의 빈 값에 들어갈 단어는 무엇일까?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#66]
> 혜령: 나 이번에 블로그 주소를 www.hyemster.com 에서 blog.hyemster.com 으로 바꾸려고 하는데 www.hyemster.com 로 접속해도 blog.hyemster.com 으로 들어오게 하고 싶은데 어떻게 해야 할까?
> 채은: _____ 레코드 사용하는 건 어때?

**Comment by ycheese** [comment]
CNAME 채은이가 똑또갛네요
