### ISSUE TITLE
[11] 각 문제와 해결 방안으로 올바르지 않은 것은?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#67]
1. 동일한 EC2 인스턴스 세션이 유지되지 않아 장바구니가 사라지는 문제 - ELB Stickiness
2. EC2 인스턴스가 이전에 있었던 일을 알 필요가 없도록 무상태를 달성하고 싶음 - 웹 쿠키
3. 사용자 쿠키 방식의 보안 및 데이터 크기 문제  - DynamoDB
4. 장기적으로 유지해야 할 사용자 정보(주소, 결제 정보, …)를 저장하고 싶음 - RDS

**Comment by ycheese** [comment]
3번
