### ISSUE TITLE
[11] Beanstalk 구성 요소에 대한 설명으로 옳지 않은 것은?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#68]
1. Beanstalk 기본 단위는 애플리케이션으로, 환경, 버전, 구성 등과 같은 Beanstalk 구성 요소의 모음이다.
2. 버전은 코드의 버전을 의미하며, 환경은 특정 애플리케이션 버전을 실행하는 리소스의 모음이다.
3. 환경 내에서는 한 번에 하나의 애플리케이션 버전만 사용할 수 있다.
4. 티어는 웹 서버 환경 티어만 설정 가능하다.

**Comment by ycheese** [comment]
4번
