### ISSUE TITLE
[11] Beanstalk 티어에 관한 설명으로 옳지 않은 것은?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#69]
1. 티어는 웹 서버 티어와 작업자 티어 두 가지가 존재한다.
2. 웹 서버 티어는 로드 밸런서, 오토 스케일링 등의 기능을 제공한다.
3. 웹 서버 티어는 사용자 요청을 직접 처리하고, 작업자 티어는 사용자 요청과 백그라운드 작업을 수행한다.
4. 작업자 티어는 SQS 메시지 수에 따라 확장된다.

**Comment by ycheese** [comment]
3번
