### ISSUE TITLE
[04] 유저에게 권한을 부여하기 위한 방법 중 잘못된 것은?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#7]
1) 유저를 권한이 설정된 그룹에 추가한다.
2) 유저에게 AWS에서 제공하는 기본 정책(Policy) 그룹을 부여한다.
3) 유저에게 직접 인라인 정책을 추가한다.
4) 유저에게 역할(Role)을 부여한다.

**Comment by ycheese** [comment]
4. 유저에게 역할(Role)을 부여한다.
역할은 유저에게 부여할 수 없어요.
