### ISSUE TITLE
[11] 인스턴스를 빠르게 생성하는 방법으로 옳지 않은 것은?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#70]
1. Golden AMI를 사용하여 EC2 인스턴스를 미리 설정된 이미지로부터 시작하기
2. User Data 스크립트를 사용하여 EC2 인스턴스에서 부트스트랩을 자동으로 수행하기
3. Elastic Beanstalk 환경을 스냅샷에서 복원하여 스키마와 데이터를 준비된 상태로 가져오기
4. Hybrid 방식으로 Golden AMI와 User Data를 혼합하여 Elastic Beanstalk 사용하기

**Comment by ycheese** [comment]
3번
