### ISSUE TITLE
[11] 다음 상황에서 적절한 조치 방안은?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#71]
> 서빙중이던 3대의 서버 중 1대가 문제가 생겨 서빙이 중단되었다.
> 이 때 무중단으로 서비스 가능하도록 하기 위해 필요한 방법은?
1. Auto Scaling
2. Route 53 도입
3. ELB 도입
4. ElastiCache 도입

**Comment by ycheese** [comment]
3번
