### ISSUE TITLE
[12] Amazon S3 버전 관리에 대해 옳지 않은 것은?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#73]
1. 버전 관리 활성화는 버킷 수준에서 관리된다.
2. 동일한 키로 파일을 업로드할 때마다 새로운 버전으로 생성된다.
3. 버전 관리 활성화 이전의 파일은 0버전으로 설정된다.
4. 버전 관리를 중단해도 이전 버전이 유지된다.

**Comment by ycheese** [comment]
3번
