### ISSUE TITLE
[12] Amazon S3 복제에 관한 설명으로 옳지 않은 것은?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#74]
1. 복제 종류에는 CRR과 SRR이 있으며, 두 개의 차이는 동일 리전 여부이다.
2. 복제 과정은 백그라운드에서 이루어지며, 읽기와 쓰기에 대한 IAM 권한이 필요하다
3. 복제 대상이 되는 두 버킷 모두 버저닝을 활성화해야 복제가 가능하다.
4. 체이닝 복제 실행할 때는 복제 대상이 되는 모든 버킷의 체이닝 복제 가능 여부를 활성화해야 체이닝 복제가 가능하다.

**Comment by ycheese** [comment]
4번
