### ISSUE TITLE
[12] Amazon S3 스토리지와 사용 사례를 올바르게 연결하지 않은 것은?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#75]
1. 컨텐츠 배포 - Amazon S3 Standard
2. 백업 - Amazon S3 IA
3. 재해 복구 - Amazon S3 One Zone Infrequent Access
4. 아카이빙 - Amazon S3 Glacier Storage Classes

**Comment by ycheese** [comment]
3번
