### ISSUE TITLE
[13] Amazon S3 스토리지 및 데이터 전송 비용이 부담스러운 경우에는 어떻게 처리해야 할까?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#76]
1.  예치금을 받아 두고, 다운로드할 때마다 차감한다.
2. 다운로드하기 전에 요청자 정보를 받아서 한 달에 한 번 다운로드 비용을 정산 및 청구한다.
3. 요청자 지불 버킷을 활성화하여 AWS 인증을 받은 실명 사용자만 다운로드 받을 수 있게 하고, AWS를 통해 청구한다.
4. 다운로드 횟수를 제한하여 특정 금액 이상 나오지 않도록 직접 컨드롤한다.

**Comment by ycheese** [comment]
3번
