### ISSUE TITLE
[13] S3 Storage Lens 무료 메트릭과 유료 메트릭의 차이에 대한 특징으로 옳은 것은?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#78]
1. 무료 메트릭은 약 28개의 사용량 지표가 포함되어 있으며, 15일 동안 데이터 조회가 가능하다.
2. 무료 메트릭은 모든 고객에게 자동으로 제공된다.
3. 유료 메트릭을 사용하면 데이터 조회 가능일이 15개월로 늘어나며, 특별한 추가 기능을 따로 제공하지는 않는다.
4. CloudWatch는 추가 금액 지불 여부와 상관없이 퍼블리시되어 추가 비용 없이 액세스 가능하다.

**Comment by ycheese** [comment]
2번
