### ISSUE TITLE
[12] 버전 관리가 활성화 된 버킷에서 객체가 삭제되었을 때 발생하는 현상으로 옳은 것은?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#86]
1. 이전 버전이 존재한다면 자동으로 이전 버전의 객체로 라우팅된다.
2. 삭제된 객체는 일정 시간 후 자동으로 삭제된다.
3. 이전 버전의 객체는 자동으로 삭제된다.
4. 외부에서 접근 시 404 Not Found 메시지가 발생한다.

**Comment by ycheese** [comment]
4번
