### ISSUE TITLE
[12] 원본 버킷에서 객체를 삭제했을 때 복제 버킷에서도 해당 객체에 접근하지 못하게 되는 경우는 언제일까?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#87]
1. `Delete Marker Replication` 옵션 활성화, 원본 객체에서 해당 객체 삭제
2. `Delete Marker Replication`를 default 값으로 설정, 원본 객체에서 해당 객체 삭제
3. `Delete Marker Replication`를 default 값으로 설정, 특정 버전을 선택하여 영구 삭제
4. `Delete Marker Replication` 옵션 활성화, 특정 버전을 선택하여 영구 삭제

**Comment by ycheese** [comment]
1번
