### ISSUE TITLE
[13] S3 업로드 속도를 높이는 방법이 아닌 것은?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#88]
1. 100MB 이상의 파일은 멀티파트 업로드를 권장한다.
2. 5GB 이상의 파일은 반드시 멀티파트 업로드를 사용한다.
3. S3 Transfer Acceleration를 활성화하여 엣지 로케이션에 파일을 업로드한다.
4. 파일을 압축하여 업로드한 후 EventBridge에서 트리거하여 압축을 해제한다.

**Comment by ycheese** [comment]
4번
