### ISSUE TITLE
[13] 아래와 같은 상황에서 가장 효율적인 해결책은?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#89]
> S3 버킷에 비디오가 업로드되면 비디오의 썸네일을 추출해서 별도의 디렉토리에 저장해두고싶다.

1. S3 Select 기능을 이용해 특정 프레임을 읽어 별도 디렉토리에 저장한다.
2. S3 Batch 기능을 이용해 썸네일 추출 프로세스를 배치로 실행한다.
3. S3 이벤트 알림 기능을 이용해 Lambda 함수를 트리거하여 썸네일 추출 프로세스를 실행한다.
4. S3 Storage Lens 기능을 이용해 버킷에 객체가 업로드 될 때를 감지하여 썸네일 추출 프로세스를 실행한다.

**Comment by ycheese** [comment]
3번
