### ISSUE TITLE
[04] IAM 관련 내용 중 바르게 설명된 것은?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#9]
1) AWS 서비스를 이용하기 위해 유저는 반드시 1개 이상의 그룹에 속해있어야 한다.
2) IAM은 리전마다 다르게 설정할 수 있다.
3) 그룹에는 오직 유저만 포함될 수 있고 다른 그룹이 포함될 수 없다.
4) 유저, 정책, 역할 관리 작업은 root 계정에서 진행하는 것이 권장된다.
5) 보안 도구인 Credential report는 유저 레벨에서, Access Advisor는 계정 레벨에서 사용한다.

**Comment by ycheese** [comment]
2. IAM은 리전마다 다르게 설정할 수 있다.
당신의 목을 지켜드립니다.
