### ISSUE TITLE
[14] 다음 상황에서는 어떤 암호화를 사용해야 할까?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#91]
> 환자 정보와 진료 기록 등 민감한 데이터를 다루고 있어서 좀 더 세분화 된 접근 제어 권한을 두고 관리하고 싶어.
> 그리고 로깅을 통해 데이터 감사와 접근 통제를 하고 싶어.

1. SSE-S3
2. SSE-KMS
3. SSE-C
4. 클라이언트 암호화

**Comment by ycheese** [comment]
정답은 2번

**Comment by behappyalltt** [comment]
1. SSE-S3
    - AWS가 관리하는 키를 이용한 암호화
2.  **SSE-KMS**
    - AWS KMS를 사용해 암호화 키 관리
    - 사용자가 키를 통제 가능함
    - CloudTrail 로깅
3. SSE-C
    - AWS 외부에서 키가 관리됨
    - 서버 측 암호화인 이유는 키를 AWS로 전송하기 때문임
    - Amazon S3는 암호화 키를 절대 저장하지 않음: 사용 후 폐기
4. 클라이언트 암호화
    - 클라이언트가 직접 데이터를 암호화하여 Amazon S3에 전송
    - 복호화도 클라이언트에서 함
