### ISSUE TITLE
[14] Access Logs에 대한 설명으로 옳지 않은 것?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#92]
1. 계정과 승인 여부에 상관없이 S3로 보낸 모든 요청은 기록된다.
2. 대상 로깅 버킷은 같은 AZ에 있어야 한다.
3. 로깅 버킷을 모니터링하는 버킷과 동일하게 설정할 경우, 로깅 루프가 생성되어 버킷의 크기가 기하급수적으로 증가하게 되기 때문에 파산할 가능성이 있다.
4. 로깅 데이터는 Amazon Athena 같은 데이터 분석 도구로 분석 가능하다.

**Comment by ycheese** [comment]
정답: 2번

**Comment by behappyalltt** [comment]
1. 계정과 승인 여부에 상관없이 S3로 보낸 모든 요청은 기록된다.
2. **대상 로깅 버킷은 같은 AZ에 있어야 한다.**
    - 같은 리전에 있어야 함
3. 로깅 버킷을 모니터링하는 버킷과 동일하게 설정할 경우, 로깅 루프가 생성되어 버킷의 크기가 기하급수적으로 증가하게 되기 때문에 파산할 가능성이 있다.
4. 로깅 데이터는 Amazon Athena 같은 데이터 분석 도구로 분석 가능하다.
