### ISSUE TITLE
[14] S3에 올린 이미지에 워터마크를 추가하고 싶은데 어떤 방법을 사용하는 것이 좋을까?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/aws-certified-solutions-architect-associate#93]
1. 알바를 고용하여 원본 이미지를 전부 다운로드 받아서 워터마크를 추가한 후 다시 업로드하여 사용자들이 워터마크를 추가한 파일에 접근하도록 한다.
2. S3 버킷에서 이벤트 알림 기능을 사용하여, 이미지가 업로드될 때마다 EC2 인스턴스를 통해 워터마크를 추가한 후, 다시 S3에 저장되도록 한다.
3. S3 객체를 Amazon S3 Batch Operations를 사용해 일괄 처리하여 모든 이미지에 워터마크를 추가하고 업데이트된 이미지를 다시 S3에 저장한다.
4. S3 객체 Lamda를 사용하여 이미지를 반환하기 전에 워터마크를 추가 후에 반환한다.

**Comment by ycheese** [comment]
정답: 4번
