### ISSUE TITLE
[14] SSE-KMS 암호화 방식에 대한 설명 중 옳은 것은?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#95]
1. 키 관리 주체는 Amazon S3이다.
2. 고객이 직접 키를 관리하기 원하는 경우 사용하는 것이 좋다.
3. AWS에서 제공하는 SSE 암호화 중 가장 비용 효율적이다.
4. S3 버킷 처리량이 많을 때 스로틀링이 발생할 위험이 있다.

**Comment by HYEMSTER** [comment]
1. 키 관리 주체는 Amazon S3이다.
    1. Amazon KMS
2. 고객이 직접 키를 관리하기 원하는 경우 사용하는 것이 좋다.
    1. SSE-C에 대한 설명
3. AWS에서 제공하는 SSE 암호화 중 가장 비용 효율적이다.
    1. SSE-S3에 대한 설명
4. S3 버킷 처리량이 많을 때 스로틀링이 발생할 위험이 있다.
    1. KMS API 한도에 의해 스로틀링이 발생할 수 있음

**Comment by ycheese** [comment]
정답: 4번
