### ISSUE TITLE
[14] 아래의 상황에서 PUT 요청이 어떻게 처리될까?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/aws-certified-solutions-architect-associate#96]
> S3 버킷에 기본 암호화가 설정되어 있다.
> 버킷 정책에서 암호화되지 않은 객체의 PUT 요청을 거부하도록 설정되어 있다.

1. 모든 PUT 요청이 거부된다.
2. 모든 PUT 요청이 허용된다.
3. 기본 암호화로 인해 모든 객체는 암호화 된 상태로 PUT 요청된다.
4. 암호화 헤더가 없는 PUT 요청이 거부된다.

**Comment by HYEMSTER** [comment]
버킷 정책이 암호화 정책보다 선제 적용된다.

**Comment by ycheese** [comment]
정답: 4번
